### ISSUE TITLE
Deploy to PyPI

### ISSUE THREAD

**Issue by grantmcconnaughey** [OnePageCRM/python_client#2]
Hello. I looked for this package on PyPI and didn't see it there. I was wondering if it could be deployed to PyPI so I don't have to use a Git repo/commit hash in my requirements.txt file. Thanks!

**Comment by peteretep** [comment]
Hi Grant, I'm glad you're finding this package useful.
To be honest, we're mostly ruby developers here so the Python package hasn't seen much love since @ruairif our main python guy moved on.
If the package is useful to you, I'll look into deploying it to PyPi.

**Comment by peteretep** [comment]
@grantmcconnaughey Sorry for the delay. I've uploaded this package to the pypi test server.
Before I deploy it to the main PyPi servers, would you be able verify that it's working as expected? I'm not a python developer and it's my first time packaging a library, so an experienced set of eyes would be great.
You can install the package from the PyPi test servers by running:
`pip install -i https://testpypi.python.org/pypi onepagecrm`

**Comment by grantmcconnaughey** [comment]
Sure thing! Give me a day or two please. Gotta attend a wedding tomorrow.

**Comment by peteretep** [comment]
@grantmcconnaughey did you get a chance to take a look?
Thanks again!

**Comment by grantmcconnaughey** [comment]
@peteretep Apologies, I got busy with work and completely forgot about this. I just created a new virtual environment and installed the package with pip. Then I started the python interpreter and imported the onepagecrm module. Everything worked fine.

**Comment by peteretep** [comment]
that's great - thanks. I'll put it onto pypi later today.

**Comment by peteretep** [comment]
can now be installed by running `pip install onepagecrm`
